AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the minecraft helm chart into an existing kubernetes cluster (qs-1qde66ffn)"
Metadata:
  QSLint:
    Exclusions: [W9002, W9003, W9004, W9006]
Parameters:
  ClusterName:
    Type: String
Resources:
  # Install minecraft helm chart
  minecraftHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    Properties:
      ClusterID: !Ref ClusterName
      Namespace: minecraft
      Chart: stable/minecraft
      Name: minecraft
      Values:
        minecraftServer.eula: "true"
        minecraftServer.Difficulty: "easy"
        server.persistentVolume.storageClass: "gp2"
        server.statefulSet.enabled: true
        server.replicaCount: 2
        server.service.sessionAffinity: ClientIP
        alertmanager.persistentVolume.storageClass: "gp2"
        alertmanager.statefulSet.enabled: true
        alertmanager.replicaCount: 2
Outputs:
  minecraftReleaseName:
    Value: !Ref minecraftHelmChart
